-- Customer Behaviour Analysis - PostgreSQL
-- Table: customer (3,900 rows), loaded from customer.ipynb
-- Results of each query are recorded underneath it.


--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
order by revenue desc;

-- Male    157890
-- Female   75191
-- Male customers are 68% of revenue, but female average order is higher
-- ($60.25 vs $59.54) - the gap is volume, not spend per customer.


--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
order by purchase_amount desc;

--Q2b. How many are they, and how much do they account for?
select COUNT(*) as customers,
       ROUND(AVG(purchase_amount),2) as avg_spend,
       SUM(purchase_amount) as total_revenue,
       ROUND(100.0 * COUNT(*) / (select COUNT(*) from customer where discount_applied = 'Yes'),1)
           as pct_of_discount_users
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- customers 839 | avg_spend 79.79 | total_revenue 66942 | pct_of_discount_users 50.0
-- Half of all discount users were already spending above the $59.76 average.


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Gloves 3.86 | Sandals 3.84 | Boots 3.82 | Hat 3.80 | Skirt 3.78
-- Ratings cluster tightly between 3.7 and 3.9; no product genuinely stands out.


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Express  60.48
-- Standard 58.46
-- A 3.4% difference. Across all six shipping types the range is only $58.46 to $60.73.


--Q5. Do subscribed customers spend more? Compare average spend and total revenue
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- No   2847 | 59.87 | 170436
-- Yes  1053 | 59.49 |  62645
-- Subscribers spend slightly LESS per order and are 26.9% of revenue from 27.0%
-- of customers. See Q11 for what they are being given in return.


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Hat 50.00 | Sneakers 49.66 | Coat 49.07 | Sweater 48.17 | Pants 47.37


--Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
-- Thresholds are a judgement call, not a property of the data. previous_purchases
-- runs from 1 to 50, so there is no zero-purchase group.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases BETWEEN 1 AND 5 THEN 'New'
    WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,
       count(*) AS "Number of Customers",
       ROUND(100.0 * count(*) / (select count(*) from customer),1) AS pct
from customer_type
group by customer_segment
order by count(*) desc;

-- Loyal      2339  60.0%
-- Returning  1137  29.2%
-- New         424  10.9%


--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Accessories: Jewelry 171, Belt 161, Sunglasses 161
-- Clothing:    Blouse 171, Pants 171, Shirt 169
-- Footwear:    Sandals 160, Shoes 150, Sneakers 145
-- Outerwear:   Jacket 163, Coat 161


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Needs both groups: a count of subscribers among repeat buyers alone proves nothing.
SELECT CASE WHEN previous_purchases > 5 THEN 'Repeat buyer' ELSE 'Not a repeat buyer' END AS buyer_type,
       COUNT(customer_id) AS customers,
       SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers,
       ROUND(100.0 * SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),1) AS subscribe_rate
FROM customer
GROUP BY buyer_type;

-- Repeat buyer        3476 | 958 | 27.6%
-- Not a repeat buyer   424 |  95 | 22.4%
-- Repeat buyers do subscribe more, but the gap is 5 percentage points, not a step change.


--Q10. What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

-- Young Adult 62143 | Middle-aged 59197 | Adult 55978 | Senior 55763
-- Age quartiles are near-identical in size, so a 10% revenue spread is not a
-- meaningful difference. Age is not a useful segmentation variable here.


--Q11. What are subscribers actually being given? Compare discount rate by subscription status.
SELECT subscription_status,
       COUNT(customer_id) AS customers,
       SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS got_discount,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY subscription_status;

-- Yes  1053 | 1053 | 100.00%
-- No   2847 |  624 |  21.92%
-- Every single subscriber has a discount applied, against 22% of non-subscribers.
-- Read with Q5: the programme is a blanket discount that buys no extra spend.
-- Recommendation: re-price the benefit or tie it to a behaviour worth paying for.


--Q12. How concentrated is revenue across product categories?
SELECT category,
       SUM(purchase_amount) AS revenue,
       ROUND(100.0 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER (),2) AS pct_of_total
FROM customer
GROUP BY category
ORDER BY revenue DESC;

-- Clothing     104264  44.73%
-- Accessories   74200  31.83%
-- Footwear      36093  15.49%
-- Outerwear     18524   7.95%
-- Total        233081
-- Two of four categories carry 76.6% of revenue.
